[package]
name = "middle-writer"
version = "0.0.0"
edition = "2021"

[dependencies]
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }
tracing = "0.1.40"
lazy_static = "1.5.0"
