[package]
name = "yaml-web-server"
version = "0.0.0"
edition = "2021"

[dependencies]
axum = "0.7.2"
glob = "0.3.1"
regex = "1.10.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1.35.1", features = ["full"] }
